# Generated by Django 2.2.5 on 2019-09-08 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OfficialBlogPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 15, 12, 20, 231825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 15, 12, 20, 231825, tzinfo=utc)),
        ),
    ]
