# Generated by Django 2.2.5 on 2019-09-08 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OfficialBlogPost', '0002_auto_20190908_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
